name: Tests

on:
    push:
    pull_request:
        branches:
            - 'main'
        
jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - uses: toitlang/action-setup@v1
          with:
            toit-version: 'v2.0.0-alpha.120'

        - run: find tests -type f \( -name '*_test.toit' -o -name '*.test.toit' \) -exec toit.run {} \;
